export const AUDIT_ACTIONS = {
    // Authentication
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',
    LOGOUT: 'LOGOUT',
    REGISTER: 'USER_REGISTERED',
    PASSWORD_RESET_REQUEST: 'PASSWORD_RESET_REQUEST',
    PASSWORD_RESET_SUCCESS: 'PASSWORD_RESET_SUCCESS',
    SESSION_REFRESHED: 'SESSION_REFRESHED',
    EMAIL_VERIFIED: 'EMAIL_VERIFIED',
    EMAIL_VERIFICATION_SENT: 'EMAIL_VERIFICATION_SENT',

    // Member Management
    MEMBER_APPROVED: 'MEMBER_APPROVED',
    MEMBER_REJECTED: 'MEMBER_REJECTED',
    MEMBER_BANNED: 'MEMBER_BANNED',
    MEMBER_UNBANNED: 'MEMBER_UNBANNED',
    MEMBER_CREATED: 'MEMBER_CREATED',
    MEMBER_UPDATED: 'MEMBER_UPDATED',
    MEMBER_DELETED: 'MEMBER_DELETED',
    ROLE_CHANGED: 'ROLE_CHANGED',

    // Profile
    PROFILE_UPDATED: 'PROFILE_UPDATED',
    GAME_PROFILE_UPDATED: 'GAME_PROFILE_UPDATED',
    FILE_UPLOADED: 'FILE_UPLOADED',

    // Security
    RATE_LIMIT_HIT: 'RATE_LIMIT_HIT',
    SUSPICIOUS_ACTIVITY: 'SUSPICIOUS_ACTIVITY',

    // Treasury
    TREASURY_ADDED: 'TREASURY_ADDED',
    TREASURY_UPDATED: 'TREASURY_UPDATED',
    TREASURY_DELETED: 'TREASURY_DELETED',

    // Phase 2: Tournaments & Profiles
    TOURNAMENT_CREATED: 'TOURNAMENT_CREATED',
    TOURNAMENT_UPDATED: 'TOURNAMENT_UPDATED',
    TOURNAMENT_DELETED: 'TOURNAMENT_DELETED',
} as const;

export type AuditActionType = typeof AUDIT_ACTIONS[keyof typeof AUDIT_ACTIONS];
