export const AUDIT_ACTIONS = {
    // Authentication
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',
    LOGOUT: 'LOGOUT',
    REGISTER: 'USER_REGISTERED',
    PASSWORD_RESET_REQUEST: 'PASSWORD_RESET_REQUEST',
    PASSWORD_RESET_SUCCESS: 'PASSWORD_RESET_SUCCESS',
    SESSION_REFRESHED: 'SESSION_REFRESHED',
    EMAIL_VERIFIED: 'EMAIL_VERIFIED',
    EMAIL_VERIFICATION_SENT: 'EMAIL_VERIFICATION_SENT',

    // User Management
    USER_APPROVED: 'USER_APPROVED',
    USER_BANNED: 'USER_BANNED',
    USER_UNBANNED: 'USER_UNBANNED',
    USER_CREATED: 'USER_CREATED',
    USER_UPDATED: 'USER_UPDATED',
    USER_DELETED: 'USER_DELETED',
    ROLE_CHANGED: 'ROLE_CHANGED',

    // Profile
    PROFILE_UPDATED: 'PROFILE_UPDATED',
    GAME_PROFILE_UPDATED: 'GAME_PROFILE_UPDATED',
    FILE_UPLOADED: 'FILE_UPLOADED',
    PUBLIC_UPLOAD_TEMP_CREATED: 'PUBLIC_UPLOAD_TEMP_CREATED',

    // Security
    RATE_LIMIT_HIT: 'RATE_LIMIT_HIT',
    SUSPICIOUS_ACTIVITY: 'SUSPICIOUS_ACTIVITY',
    SENSITIVE_FIELD_CHANGED: 'SENSITIVE_FIELD_CHANGED',
    USER_ACTIVITY_TOUCHED: 'USER_ACTIVITY_TOUCHED',

    // Treasury
    TREASURY_ADDED: 'TREASURY_ADDED',
    TREASURY_UPDATED: 'TREASURY_UPDATED',
    TREASURY_DELETED: 'TREASURY_DELETED',

    // Phase 2: Tournaments & Profiles
    TOURNAMENT_CREATED: 'TOURNAMENT_CREATED',
    TOURNAMENT_UPDATED: 'TOURNAMENT_UPDATED',
    TOURNAMENT_DELETED: 'TOURNAMENT_DELETED',
    TOURNAMENT_REGISTERED: 'TOURNAMENT_REGISTERED',
} as const;

export type AuditActionType = typeof AUDIT_ACTIONS[keyof typeof AUDIT_ACTIONS];
