ALTER TABLE `Tournament`
  ADD COLUMN `forfeitEnabled` BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `forfeitGraceMinutes` INT NOT NULL DEFAULT 15,
  ADD COLUMN `forfeitMode` ENUM('CHECKIN_ONLY','SCHEDULE_NO_SHOW') NOT NULL DEFAULT 'CHECKIN_ONLY';
